[build-system]
requires = ["setuptools>=75.3.2"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py310"]

[tool.check-manifest]
ignore = [
    ".editorconfig",
    ".flake8",
    ".pre-commit-config.yaml",
    "tox.ini",
    "build_git.sh",
    "buildout.cfg",
]

[tool.isort]
profile = "plone"
