name: Run Tox Tests

on:
  push:
    branches:
      - master
      - main
      - subpath
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15']

    steps:
    - uses: actions/checkout@v7.0.1
      with:
        persist-credentials: false

    - name: Install uv + caching
      uses: astral-sh/setup-uv@v10.0.0
      with:
        enable-cache: true
        cache-dependency-glob: |
          setup.*
          tox.ini
          pyproject.toml
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y mercurial subversion

    - name: Test with tox
      run: uvx --with tox-uv --with tox-gh-actions tox
